# ------------------------------------------------------------
# In this file, you can make some modifications to the Streamlit
# app's global environment. 
#
# All of the possible config options can be found here:
# https://docs.streamlit.io/develop/api-reference/configuration/config.toml
# ------------------------------------------------------------


[client]
# Turning the default sidebar navigation off so we 
# can use our own
showSidebarNavigation = false

[theme]
# Setting some basic config options related to the theme of the app
primaryColor="#E63946"     # fit red
backgroundColor="#FFFFFF"  # white
secondaryBackgroundColor="#F8F9FA"
textColor="#1A1A1A"
font="sans serif"

[server]
runOnSave = true